version: '3.8'
services:
  database:
    container_name: dot-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: dot-db
    ports:
      - '5435:5435'
